STATION_NAMES = ['Rokossovskaya', 'Sobornaya', 'Crystal', 'Zarechnaya', 'Pushkin library']
TIME_BETWEEN_STATIONS_MINUTES = [6, 3, 2, 7]
TIME_BETWEEN_STATIONS_SECONDS = [t * 60 for t in TIME_BETWEEN_STATIONS_MINUTES]

NUMB_OF_TRAINS = 10
SPEED = 1000

PASSENGER_START_GENERATION_TIME_SECONDS = sum(TIME_BETWEEN_STATIONS_SECONDS)
TRAIN_START_INTERVAL_SECONDS = int(38 / NUMB_OF_TRAINS * 60)

TIME_AT_STATION_SECONDS = 15
MAX_PEOPLE_AT_STATION = 1000
MAX_PEOPLE_IN_TRAIN = 400

STAT_GET_INTERVAL = 30
